jdbc:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:user_db;DB_CLOSE_DELAY=-1

hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: create

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:somethingsecret}
      expire-length: ${JWT_EXPIRE_LENGTH:300000}
